### ISSUE TITLE
Lighthouse plugin fails during deploy

### ISSUE THREAD

**Issue by dannya** [netlify/netlify-plugin-lighthouse#450]
Lighthouse plugin fails on my site during deploy:

```
11:59:56 PM: ────────────────────────────────────────────────────────────────
11:59:56 PM:   Plugin "@netlify/plugin-lighthouse" failed                    
11:59:56 PM: ────────────────────────────────────────────────────────────────
11:59:56 PM: ​
11:59:56 PM:   Error message
11:59:56 PM:   TypeError: Failed with error:
11:59:56 PM: ​
11:59:56 PM:   Cannot read properties of undefined (reading 'reduce')
11:59:56 PM: ​
11:59:56 PM:   Plugin details
11:59:56 PM:   Package:        @netlify/plugin-lighthouse
11:59:56 PM:   Version:        3.2.0
11:59:56 PM:   Repository:     git+https://github.com/netlify/netlify-plugin-lighthouse.git
11:59:56 PM:   npm link:       https://www.npmjs.com/package/@netlify/plugin-lighthouse
11:59:56 PM:   Report issues:  https://github.com/netlify/netlify-plugin-lighthouse/issues
11:59:56 PM: ​
11:59:56 PM:   Error location
11:59:56 PM:   In "onPostBuild" event in "@netlify/plugin-lighthouse" from Netlify app
11:59:56 PM:       at /.netlify/plugins/node_modules/@netlify/plugin-lighthouse/src/index.js:223:30
11:59:56 PM:       at processResults (/.netlify/plugins/node_modules/@netlify/plugin-lighthouse/src/index.js:221:10)
11:59:56 PM:       at onPostBuild (/.netlify/plugins/node_modules/@netlify/plugin-lighthouse/src/index.js:289:45)
11:59:56 PM: ​
11:59:56 PM:   Resolved config
11:59:56 PM:   build:
11:59:56 PM:     command: npm run build
11:59:56 PM:     commandOrigin: ui
11:59:56 PM:     environment:
11:59:56 PM:       - NODE_VERSION
11:59:56 PM:     publish: /opt/build/repo/ui/build
11:59:56 PM:     publishOrigin: ui
11:59:56 PM:   plugins:
11:59:56 PM:     - inputs: {}
11:59:56 PM:       origin: ui
11:59:56 PM:       package: '@netlify/plugin-lighthouse'
11:59:56 PM:   redirects:
11:59:56 PM:     - from: /ore
11:59:56 PM:       status: 200
11:59:56 PM:       to: /index.html
11:59:57 PM:     - from: /*
```

Netlify build environment details:

```
11:58:22 PM: Build ready to start
11:58:23 PM: build-image version: d7b3dbfb0846505993c9a131894d1858074c90b4 (focal)
11:58:23 PM: build-image tag: v4.10.1
11:58:23 PM: buildbot version: fe6512288e75c8fa5aadaebb51ed1f96e9314fd4
11:58:23 PM: Building without cache
11:58:23 PM: Starting to prepare the repo for build
11:58:24 PM: No cached dependencies found. Cloning fresh repo
11:58:24 PM: git clone https://github.com/dannya/wonderscore
11:58:24 PM: Preparing Git Reference refs/heads/master
11:58:25 PM: Parsing package.json dependencies
11:58:26 PM: Starting build script
11:58:26 PM: Installing dependencies
11:58:26 PM: Python version set to 2.7
11:58:26 PM: v16.16.0 is already installed.
11:58:26 PM: Now using node v16.16.0 (npm v8.11.0)
11:58:26 PM: Started restoring cached build plugins
11:58:26 PM: Finished restoring cached build plugins
11:58:26 PM: Attempting ruby version 2.7.2, read from environment
11:58:27 PM: Using ruby version 2.7.2
11:58:27 PM: Using PHP version 8.0
11:58:27 PM: Started restoring cached yarn cache
11:58:27 PM: Finished restoring cached yarn cache
11:58:28 PM: No yarn workspaces detected
11:58:28 PM: Started restoring cached node modules
11:58:28 PM: Finished restoring cached node modules
11:58:28 PM: Installing NPM modules using Yarn version 1.22.10
11:58:28 PM: npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
11:58:28 PM: npm WARN config location in the cache, and they are managed by
11:58:28 PM: npm WARN config     [`cacache`](http://npm.im/cacache).
11:58:28 PM: yarn install v1.22.10
11:58:28 PM: [1/4] Resolving packages...
11:58:29 PM: [2/4] Fetching packages...
11:58:39 PM: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
11:58:39 PM: info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
11:58:39 PM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
11:58:39 PM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
11:58:39 PM: [3/4] Linking dependencies...
11:58:42 PM: [4/4] Building fresh packages...
11:59:00 PM: Done in 31.72s.
11:59:00 PM: NPM modules installed using Yarn
11:59:00 PM: Started restoring cached go cache
11:59:00 PM: Finished restoring cached go cache
11:59:00 PM: Installing Go version 1.17 (requested 1.17)
11:59:05 PM: unset GOOS;
11:59:05 PM: unset GOARCH;
11:59:05 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.17.linux.amd64';
11:59:05 PM: export PATH="/opt/buildhome/.gimme/versions/go1.17.linux.amd64/bin:${PATH}";
11:59:05 PM: go version >&2;
11:59:05 PM: export GIMME_ENV="/opt/buildhome/.gimme/env/go1.17.linux.amd64.env"
11:59:05 PM: go version go1.17 linux/amd64
11:59:05 PM: Installing missing commands
11:59:05 PM: Verify run directory
11:59:06 PM: ​
11:59:06 PM: ────────────────────────────────────────────────────────────────
11:59:06 PM:   Netlify Build                                                 
11:59:06 PM: ────────────────────────────────────────────────────────────────
11:59:06 PM: ​
11:59:06 PM: ❯ Version
11:59:06 PM:   @netlify/build 27.9.1
11:59:06 PM: ​
11:59:06 PM: ❯ Flags
11:59:06 PM:   baseRelDir: true
11:59:06 PM:   buildId: 62eef20d4739791ee0345d31
11:59:06 PM:   deployId: 62eef20d4739791ee0345d33
11:59:06 PM:   systemLogFile: 3
11:59:06 PM: ​
11:59:06 PM: ❯ Current directory
11:59:06 PM:   /opt/build/repo
11:59:06 PM: ​
11:59:06 PM: ❯ Config file
11:59:06 PM:   /opt/build/repo/netlify.toml
11:59:06 PM: ​
11:59:06 PM: ❯ Context
11:59:06 PM:   production
11:59:06 PM: ​
11:59:06 PM: ❯ Installing plugins
11:59:06 PM:    - @netlify/plugin-lighthouse@3.2.0
11:59:18 PM: ​
11:59:18 PM: ❯ Loading plugins
11:59:18 PM:    - @netlify/plugin-lighthouse@3.2.0 from Netlify app
```

**Comment by mzampetti** [comment]
Same problem for us, multiple clients builds are broken right now.

**Comment by kevinsamoei** [comment]
Hello, @dannya and @mzampetti Sorry for the inconvenience caused. A new version `3.2.1` has been released and should fix the issue. Mind installing that version to make sure? 

- if using the netlify toml config, nothing to do
- if you have specified the plugin in your `package.json`, do the version update
- if you installed through the Netlify UI, make sure to upgrade to the new version

**Comment by kevinsamoei** [comment]
That means that the plugin or lighthouse did not return any audit reports. Are the logs for that deploy public? if so mind sharing the URL?  If not if I could get the site's name or ID  that would be helpful. Also, what are the contents of `ui/build`, is it files or folders?

I do agree that we need to improve the error messages for this plugin and that will be coming in the future

**Comment by dannya** [comment]
The site ID is `c24cc247-ba17-4d21-a8e1-b05d8bcd1e52`.

The `ui/build` directory contains all the build dist files / folders, and looks like this:

![image](https://user-images.githubusercontent.com/394687/183882254-5bc753c5-b523-48df-8abb-83e020c81257.png)

Thanks,
Danny

**Comment by kevinsamoei** [comment]
Looking at the logs this is the error that lighthouse returns 
```
LH:GatherRunner:error The page did not paint any content. Please ensure you keep the browser window in the foreground during the load and try again. (NO_FCP) http://localhost:5000/
```

This seems not specific to the plugin as I get the same error when running the lighthouse audit against `https://wonderscore.co.uk/` in chrome tools

<img width="1974" alt="Screen Shot 2022-08-10 at 15 11 49" src="https://user-images.githubusercontent.com/15800486/183897889-a7b471ac-9708-41fa-a563-7ba3978d6d8b.png">


This could related issue with animated content - see https://github.com/GoogleChrome/lighthouse/issues/13253

Thanks!
